// Mock data para demonstração — utilizado como fallback quando a API não está disponível

export const MOCK_METRICS = {
  totalOpportunities: 147,
  revenueWon: 284500,
  conversionRate: 32.4,
  averageTicket: 8750,
  salesVelocity: 52000,
  averageCycleDuration: 18 * 24 * 60 * 60 * 1000, // 18 dias em ms
  trends: {
    totalOpportunities: +12.5,
    revenueWon: +8.3,
    conversionRate: -2.1,
    averageTicket: +5.7,
    salesVelocity: +14.2,
    averageCycleDuration: -6.8,
  },
  funnel: [
    { stageName: "Prospecção", count: 42, color: "#8b5cf6" },
    { stageName: "Qualificação", count: 31, color: "#6366f1" },
    { stageName: "Proposta", count: 28, color: "#0ea5e9" },
    { stageName: "Negociação", count: 19, color: "#f59e0b" },
    { stageName: "Fechamento", count: 27, color: "#10b981" },
  ],
  distributionByStage: [
    { stageName: "Prospecção", count: 42, color: "#8b5cf6" },
    { stageName: "Qualificação", count: 31, color: "#6366f1" },
    { stageName: "Proposta", count: 28, color: "#0ea5e9" },
    { stageName: "Negociação", count: 19, color: "#f59e0b" },
    { stageName: "Fechamento", count: 27, color: "#10b981" },
  ],
  leadSource: [
    { source: "Website", count: 45 },
    { source: "Indicação", count: 38 },
    { source: "LinkedIn", count: 29 },
    { source: "Google Ads", count: 22 },
    { source: "Email Marketing", count: 13 },
  ],
  recentActivity: [
    {
      id: "act-1",
      type: "won",
      text: "Oportunidade \"Enterprise Suite - TechCorp\" fechada",
      value: 85000,
      time: "há 2 horas",
      avatar: "AT",
      color: "emerald",
    },
    {
      id: "act-2",
      type: "contact",
      text: "Novo contato: Mariana Costa adicionada",
      time: "há 4 horas",
      avatar: "MC",
      color: "violet",
    },
    {
      id: "act-3",
      type: "stage",
      text: "\"Implementação ERP - Grupo Nexus\" avançou para Negociação",
      time: "há 6 horas",
      avatar: "GN",
      color: "amber",
    },
    {
      id: "act-4",
      type: "won",
      text: "Oportunidade \"CRM Pro - Alfa Sistemas\" fechada",
      value: 42000,
      time: "ontem",
      avatar: "AS",
      color: "emerald",
    },
    {
      id: "act-5",
      type: "contact",
      text: "Novo contato: Rafael Oliveira adicionado",
      time: "ontem",
      avatar: "RO",
      color: "violet",
    },
  ],
};

export type LeadScore = "quente" | "morno" | "frio";

export type MockContact = {
  id: string;
  name: string;
  email: string;
  company: string;
  phone: string;
  status: "ativo" | "prospect" | "inativo";
  tags: string[];
  lastContact: string;
  initials: string;
  avatarColor: string;
  score: LeadScore;
};

export const MOCK_CONTACTS: MockContact[] = [
  {
    id: "c-1",
    name: "Ana Paula Ferreira",
    email: "ana.paula@techcorp.com.br",
    company: "TechCorp Brasil",
    phone: "+55 11 9 8765-4321",
    status: "ativo",
    tags: ["VIP", "Tech", "Enterprise"],
    lastContact: "2026-03-09",
    initials: "AF",
    avatarColor: "from-violet-500 to-indigo-600",
    score: "quente",
  },
  {
    id: "c-2",
    name: "Carlos Eduardo Mendes",
    email: "c.mendes@grupnexus.com.br",
    company: "Grupo Nexus",
    phone: "+55 21 9 9876-5432",
    status: "ativo",
    tags: ["ERP", "Mid-Market"],
    lastContact: "2026-03-08",
    initials: "CM",
    avatarColor: "from-blue-500 to-cyan-600",
    score: "quente",
  },
  {
    id: "c-3",
    name: "Beatriz Santos",
    email: "beatriz@inovacaodigital.io",
    company: "Inovação Digital",
    phone: "+55 51 9 7654-3210",
    status: "prospect",
    tags: ["SaaS", "Startup"],
    lastContact: "2026-03-07",
    initials: "BS",
    avatarColor: "from-pink-500 to-rose-600",
    score: "morno",
  },
  {
    id: "c-4",
    name: "Rafael Oliveira Lima",
    email: "rafael.lima@alfasistemas.com.br",
    company: "Alfa Sistemas",
    phone: "+55 31 9 8765-1234",
    status: "ativo",
    tags: ["CRM", "Enterprise"],
    lastContact: "2026-03-06",
    initials: "RL",
    avatarColor: "from-emerald-500 to-teal-600",
    score: "quente",
  },
  {
    id: "c-5",
    name: "Mariana Costa",
    email: "mariana@betasolutions.com.br",
    company: "Beta Solutions",
    phone: "+55 41 9 7890-2345",
    status: "prospect",
    tags: ["Consultoria", "B2B"],
    lastContact: "2026-03-05",
    initials: "MC",
    avatarColor: "from-amber-500 to-orange-600",
    score: "morno",
  },
  {
    id: "c-6",
    name: "Pedro Augusto Rocha",
    email: "pedro.rocha@gammatech.com.br",
    company: "Gamma Tech",
    phone: "+55 61 9 6543-9876",
    status: "ativo",
    tags: ["Tech", "SMB"],
    lastContact: "2026-03-04",
    initials: "PR",
    avatarColor: "from-purple-500 to-violet-600",
    score: "morno",
  },
  {
    id: "c-7",
    name: "Juliana Alves",
    email: "j.alves@deltacorp.com.br",
    company: "Delta Corp",
    phone: "+55 11 9 5432-8765",
    status: "inativo",
    tags: ["Manufacturing"],
    lastContact: "2026-02-15",
    initials: "JA",
    avatarColor: "from-slate-500 to-gray-600",
    score: "frio",
  },
  {
    id: "c-8",
    name: "Thiago Nascimento",
    email: "thiago@epsilongroup.com.br",
    company: "Epsilon Group",
    phone: "+55 71 9 4321-7654",
    status: "ativo",
    tags: ["VIP", "Retail"],
    lastContact: "2026-03-10",
    initials: "TN",
    avatarColor: "from-cyan-500 to-blue-600",
    score: "quente",
  },
  {
    id: "c-9",
    name: "Fernanda Ribeiro",
    email: "f.ribeiro@zetaventures.com.br",
    company: "Zeta Ventures",
    phone: "+55 85 9 3210-6543",
    status: "prospect",
    tags: ["FinTech", "Startup"],
    lastContact: "2026-03-03",
    initials: "FR",
    avatarColor: "from-fuchsia-500 to-pink-600",
    score: "frio",
  },
  {
    id: "c-10",
    name: "Lucas Sousa",
    email: "lucas@etapartners.com.br",
    company: "Eta Partners",
    phone: "+55 27 9 2109-5432",
    status: "ativo",
    tags: ["Agro", "Enterprise"],
    lastContact: "2026-03-09",
    initials: "LS",
    avatarColor: "from-lime-500 to-green-600",
    score: "quente",
  },
  {
    id: "c-11",
    name: "Amanda Pereira",
    email: "amanda@thetalogistica.com.br",
    company: "Theta Logística",
    phone: "+55 48 9 1098-4321",
    status: "prospect",
    tags: ["Logística", "B2B"],
    lastContact: "2026-03-01",
    initials: "AP",
    avatarColor: "from-red-500 to-rose-600",
    score: "frio",
  },
  {
    id: "c-12",
    name: "Rodrigo Martins",
    email: "r.martins@iotaconsult.com.br",
    company: "Iota Consulting",
    phone: "+55 62 9 0987-3210",
    status: "ativo",
    tags: ["VIP", "Consultoria"],
    lastContact: "2026-03-08",
    initials: "RM",
    avatarColor: "from-indigo-500 to-violet-600",
    score: "quente",
  },
];

export const MOCK_PIPELINE = {
  id: "pipeline-demo",
  name: "Pipeline Principal",
  isDefault: true,
  stages: [
    { id: "stage-prospeccao", name: "Prospecção", order: 1, color: "#8b5cf6" },
    { id: "stage-qualificacao", name: "Qualificação", order: 2, color: "#6366f1" },
    { id: "stage-proposta", name: "Proposta", order: 3, color: "#0ea5e9" },
    { id: "stage-negociacao", name: "Negociação", order: 4, color: "#f59e0b" },
    { id: "stage-fechamento", name: "Fechamento", order: 5, color: "#10b981" },
  ],
};

export const MOCK_OPPORTUNITIES = [
  // Prospecção
  {
    id: "opp-1",
    title: "CRM Enterprise - TechCorp",
    value: 85000,
    stageId: "stage-prospeccao",
    priority: "high",
    daysInStage: 3,
    contact: { name: "Ana Paula Ferreira" },
    stage: { name: "Prospecção" },
  },
  {
    id: "opp-2",
    title: "Automação de Vendas - StartUp XY",
    value: 22000,
    stageId: "stage-prospeccao",
    priority: "medium",
    daysInStage: 7,
    contact: { name: "Beatriz Santos" },
    stage: { name: "Prospecção" },
  },
  {
    id: "opp-3",
    title: "Suite Colaboração - Ômega Tech",
    value: 15000,
    stageId: "stage-prospeccao",
    priority: "low",
    daysInStage: 12,
    contact: { name: "Amanda Pereira" },
    stage: { name: "Prospecção" },
  },
  // Qualificação
  {
    id: "opp-4",
    title: "ERP Integrado - Grupo Nexus",
    value: 120000,
    stageId: "stage-qualificacao",
    priority: "high",
    daysInStage: 5,
    contact: { name: "Carlos Eduardo Mendes" },
    stage: { name: "Qualificação" },
  },
  {
    id: "opp-5",
    title: "BI Dashboard - Epsilon Group",
    value: 38000,
    stageId: "stage-qualificacao",
    priority: "medium",
    daysInStage: 9,
    contact: { name: "Thiago Nascimento" },
    stage: { name: "Qualificação" },
  },
  {
    id: "opp-6",
    title: "Suporte Premium - Eta Partners",
    value: 18000,
    stageId: "stage-qualificacao",
    priority: "low",
    daysInStage: 14,
    contact: { name: "Lucas Sousa" },
    stage: { name: "Qualificação" },
  },
  // Proposta
  {
    id: "opp-7",
    title: "CRM Pro - Alfa Sistemas",
    value: 42000,
    stageId: "stage-proposta",
    priority: "high",
    daysInStage: 4,
    contact: { name: "Rafael Oliveira Lima" },
    stage: { name: "Proposta" },
  },
  {
    id: "opp-8",
    title: "Marketing Suite - Zeta Ventures",
    value: 27000,
    stageId: "stage-proposta",
    priority: "medium",
    daysInStage: 8,
    contact: { name: "Fernanda Ribeiro" },
    stage: { name: "Proposta" },
  },
  {
    id: "opp-9",
    title: "Gestão de Clientes - Gamma Tech",
    value: 19500,
    stageId: "stage-proposta",
    priority: "medium",
    daysInStage: 11,
    contact: { name: "Pedro Augusto Rocha" },
    stage: { name: "Proposta" },
  },
  // Negociação
  {
    id: "opp-10",
    title: "Plataforma Agro - Eta Partners",
    value: 68000,
    stageId: "stage-negociacao",
    priority: "high",
    daysInStage: 6,
    contact: { name: "Lucas Sousa" },
    stage: { name: "Negociação" },
  },
  {
    id: "opp-11",
    title: "Consultoria Digital - Iota",
    value: 31000,
    stageId: "stage-negociacao",
    priority: "medium",
    daysInStage: 16,
    contact: { name: "Rodrigo Martins" },
    stage: { name: "Negociação" },
  },
  // Fechamento
  {
    id: "opp-12",
    title: "Enterprise Suite - Mariana Holding",
    value: 96000,
    stageId: "stage-fechamento",
    priority: "high",
    daysInStage: 2,
    contact: { name: "Mariana Costa" },
    stage: { name: "Fechamento" },
  },
  {
    id: "opp-13",
    title: "SaaS Integration - Beta Solutions",
    value: 45000,
    stageId: "stage-fechamento",
    priority: "high",
    daysInStage: 3,
    contact: { name: "Mariana Costa" },
    stage: { name: "Fechamento" },
  },
];
